name: PHP Syntax Check
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP
        run: sudo apt-get update && sudo apt-get install -y php-cli

      - name: PHP Syntax Check
        run: find. -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Success Message
        run: echo "Bhai saara PHP code clean hai! ✅"
